version: "3"

services:
 webserver:
  image: linuxserver/letsencrypt
  container_name: nginx
  cap_add:
   - NET_ADMIN
  environment:
   - TZ=Europe/London
   - URL=dreamingoftech.uk
   - SUBDOMAINS=www,api
   - VALIDATION=http
  volumes:
   - ~/web/nginx/config:/config
   - ~/web/nginxlog:/var/log/nginx
  ports:
   - 443:443
   - 80:80
#  extra_hosts:
#   - "dot:178.128.175.91"
  networks:
   - backend
  
 mongodb:
  image: mongo:latest
  container_name: "mongodb"
  environment:
   - MONGO_DATA_DIR=/data/db
   - MONGO_LOG_DIR=/dev/null
  volumes:
   - ./data/db:/data/db
  ports:
   - 27017:27017
  networks:
   - backend

 siteapi:
  build: ~/web/server
  volumes:
   - ~/web/server:/usr/src/app
   - /usr/src/app/node_modules
  ports:
   - 4000:4000
  command: npm start
  networks:
   - backend

networks:
 backend:
  driver: bridge
